services:
  boot:
    container_name: kustaurant-boot
    image: docker.io/dingwoon/kustaurant:${DEPLOY_TAG:-latest}
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped