services:
  redis:
    image: redis:7-alpine
    container_name: kustaurant-redis
    ports:
      - "6379:6379"
    restart: always

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: kustaurant-prometheus
    ports:
      - "9090:9090"  # 로컬/외부 접근 허용 (보안그룹 유의)
    volumes:
      - ../../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.2.0
    container_name: kustaurant-grafana
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ../../monitoring/grafana:/var/lib/grafana
      - ../../monitoring/grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.6
    container_name: kustaurant-loki
    command: -config.file=/etc/loki/config.yml
    ports:
      - "3100:3100"
    volumes:
      - ../../monitoring/loki/config.yml:/etc/loki/config.yml:ro
      - ../../monitoring/loki/data:/loki
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.6
    container_name: kustaurant-promtail
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ../../monitoring/promtail/config.yml:/etc/promtail/config.yml:ro
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - loki
    restart: unless-stopped

  mysqld-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld-exporter
    environment:
      - TZ=${TZ}
      - DATA_SOURCE_NAME=${MYSQL_EXPORTER_USER}:${MYSQL_EXPORTER_PASS}@(${MYSQL_HOST}:${MYSQL_PORT})/
    restart: unless-stopped