spring:
  profiles:
    active: local
  config:
    import:
      - "optional:auth.yml"
      - "optional:.env"
  servlet:
    multipart:
      enabled: true
      max-file-size: "10MB"
      max-request-size: "10MB"

  thymeleaf:
    encoding: "UTF-8"

  jpa:
    hibernate.ddl-auto: validate
  cloud:
    aws:
      region:
        static: "ap-northeast-2"
      credentials:
        access-key: "${AWS_ACCESS_KEY}"
        secret-key: "${AWS_SECRET_KEY}"
      s3:
        bucket: kustaurant

# logging level
logging.level.com.kustaurant: trace

# custom setting
restaurant:
  initialDisplayMenuCount: 2
  rating:
    policy:
      evaluation:
        recency_lambda: 0.05
        reaction_divisor: 10
        evaluator_k: 5
        completeness_weight:
          comment: 0.5
          situation: 0.2
          image: 0.3
      restaurant:
        popularity_weight:
          visits: 0.1
          favorites: 0.2
          evaluations: 0.7
      tier:
        levels:
          1:
            min_score: 4.0
            max_ratio: 0.20
          2:
            min_score: 3.5
            max_ratio: 0.20
          3:
            min_score: 3.0
            max_ratio: 0.20
          4:
            min_score: 2.5
            max_ratio: 0.20
          5:
            min_score: 2.0
            max_ratio: 0.20