# default-profile section
logging.level.com.kustaurant: trace

# aws s3
cloud.aws:
  s3:
    bucket: "kustaurant"
  stack:
    auto: false
  region:
    static: "ap-northeast-2"
  credentials:
    access-key: "${S3_ACCESS_KEY}"
    secret-key: "${S3_SECRET_KEY}"

# spring
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/kmr_db?serverTimezone=UTC"
    username: "root"
    password: "1234"
  servlet:
    multipart:
      enabled: true
      max-file-size: "10MB"
      max-request-size: "10MB"
  thymeleaf:
    encoding: "UTF-8"
  jpa:
    hibernate.ddl-auto: "validate"
  config:
    import: "optional:auth.yml" # import auth.yml

# custom setting
restaurant:
  initialDisplayMenuCount: 2

---
# prod-profile section
logging.level.com.kustaurant: info

# spring
spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "${DB_URL}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"

# logging
logging:
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: "100MB"
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}-%i.log"
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss.SSS,Asia/Seoul"
  file:
    name: "logs/konstaurant.log"
