server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'compose_service'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'

  - job_name: kustaurant
    static_configs:
      - targets: [ localhost ]
        labels:
          job: kustaurant
          app: kustaurant
          env: prod
          __path__: /var/log/kustaurant/*.log

    pipeline_stages:
      - json:
          expressions:
            ts: '@timestamp'
            level: level
            logger: logger_name
            msg: message
            thread: thread_name
      - timestamp:
          source: ts
          format: RFC3339Nano
      - labels:
          level:
