
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASSWORD}
  data:
    redis:
      host: 127.0.0.1
      port: 6379

  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    enabled: true
    locations: classpath:db/migration/prod
    validate-on-migrate: true
    out-of-order: false

logging:
  level:
    com.kustaurant: info
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: "100MB"
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}-%i.log"
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss.SSS,Asia/Seoul"
  file:
    name: "logs/kustaurant.log"