package com.kustaurant.kustaurant.mock;

import com.kustaurant.kustaurant.common.post.domain.Post;
import com.kustaurant.kustaurant.common.post.infrastructure.PostEntity;
import com.kustaurant.kustaurant.common.post.service.port.PostRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;

import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;

public class FakePostRepository implements PostRepository {
    private final AtomicInteger autoGeneratedId = new AtomicInteger(0);
    private final List<Post> data = Collections.synchronizedList(new ArrayList<>());

    @Override
    public Optional<Post> findById(Integer id) {
        return data.stream().filter(item -> item.getPostId().equals(id)).findAny();
    }

    @Override
    public Post save(Post post) {
        if( post.getPostId() == null || post.getPostId() ==0 ){
            Post newPost = Post.builder()
                    .postId(autoGeneratedId.incrementAndGet())
                    .userId(post.getUserId())
                    .postBody(post.getPostBody())
                    .createdAt(post.getCreatedAt())
                    .updatedAt(post.getUpdatedAt())
                    .build();
            data.add(newPost);
            return newPost;
        }else{
            data.removeIf(item -> Objects.equals(item.getPostId(), post.getPostId()));
            data.add(post);
            return post;
        }
    }

    @Override
    public Page<PostEntity> findAll(Specification<PostEntity> spec, Pageable pageable) {
        return null;
    }

    @Override
    public Page<PostEntity> findAll(Pageable pageable) {
        return null;
    }

    @Override
    public Page<PostEntity> findByStatus(String status, Pageable pageable) {
        return null;
    }

    @Override
    public List<PostEntity> findActivePostsByUserId(Integer userId) {
        return List.of();
    }

    @Override
    public Optional<PostEntity> findByStatusAndPostId(String status, Integer postId) {
        return Optional.empty();
    }
}
