{
 "title": "Cralwer Observability",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Log of Spring Crawler",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"crawler\"}\r\n| json\r\n| line_format `{{ __timestamp__ | date \"2006-01-02T15:04:05.000Z07:00\" }} [{{ .level }}] [{{ .thread_name }}] {{ .logger_name }} : {{ .message | replace \"\\n\" \"\\n\" }}`"
    }
   ]
  },
  {
   "title": "Error Log of Spring Cralwer",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{job=\"crawler\", level=\"ERROR\"} \r\n| json \r\n| line_format `{{ __timestamp__ | date \"2006-01-02T15:04:05.000Z07:00\" }} [{{ .level }}] [{{ .thread_name }}] {{ .logger_name }} : {{ .message | replace \"\\n\" \"\\n\" }}{{ if eq .level \"ERROR\" }}\\n{{ .stack_trace | replace \"\\n\" \"\\n\" }}{{ end }}`"
    }
   ]
  },
  {
   "title": "Active Browsers & Memory Info",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "playwright_active_browsers{job=\"crawler-host\"}",
     "legendFormat": "active browsers"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", job=\"crawler-host\"}) / 1024 / 1024",
     "legendFormat": "heap used (MB)"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{job=\"crawler-node-exporter\"} - node_memory_MemAvailable_bytes{job=\"crawler-node-exporter\"}) / node_memory_MemTotal_bytes{job=\"crawler-node-exporter\"} * 100",
     "legendFormat": "system memory used (%)"
    }
   ]
  }
 ]
}