name: 자동테스트

on:
  pull_request:
    branches: [ main, develop ]

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  small-test:
    name: 🧪 소형 테스트
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run small tests
        run: ./gradlew --no-daemon :server:kustaurant:test

      - name: Publish Small Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: server/kustaurant/build/test-results/test/TEST-*.xml
          check_name: 🧪 소형(단위) 테스트 결과
          check_run: false

  #      - name: Publish Test Report
  #        if: always()
  #        uses: dorny/test-reporter@v1
  #        with:
  #          name: 🧪 소형 테스트 리포트
  #          path: server/kustaurant/build/test-results/test/*.xml
  #          reporter: java-junit

  middle-test:
    name: 🚀 중형 테스트
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: thisIsA32ByteLengthSecretKeyForJWT!
      JWT_ACCESS_TOKEN_EXPIRATION : 900
      JWT_REFRESH_TOKEN_EXPIRATION : 604800
      NAVER_CLIENT_ID : kustaurant
      NAVER_CLIENT_SECRET : secreat
      APPLE_CLIENT_ID : kustaurant
      APPLE_PUBLIC_KEYS_URL : https://appleid.apple.com/auth/keys
      ALERT_DISCORD_WEBHOOK: ${{ secrets.ALERT_DISCORD_WEBHOOK }}
      GRAFANA_ADMIN_USER: ${{ secrets.GRAFANA_ADMIN_USER }}
      GRAFANA_ADMIN_PASSWORD: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Docker info (for Testcontainers)
        run: docker info

      - name: Run middle tests
        run: ./gradlew --no-daemon :server:kustaurant:integrationTest

      - name: Publish Middle Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: server/kustaurant/build/test-results/integrationTest/TEST-*.xml
          check_name: 🚀 중형(통합) 테스트 결과
          check_run: false
#        작동 시간이 길어지고, 테스트 결과 표출과 리포트 남기기는 같이 적용이 안됨. 둘중 하나만 적용됨
#      - name: Publish Test Report
#        if: always()
#        uses: dorny/test-reporter@v1
#        with:
#          name: 🚀 중형 테스트 리포트
#          path: server/kustaurant/build/test-results/integrationTest/*.xml
#          reporter: java-junit
